#!/usr/bin/env python3

from subprocess import run
from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("image", metavar="image to flash", type=str)

image = parser.parse_args().image

while True:
    input(f"Press enter to compile {image}...")
    res = run(f"make {image}.hex".split(" "), capture_output=True, text=True)
    print(res.stdout)
    if res.returncode != 0 and len(res.stderr) > 0:
        print("ERROR: ")
        print(res.stderr)
        # error when compiling, restart loop to recompile
        continue

    input("\n"*3 + f"Press enter to flash {image}...")
    run(f"make flash-{image}".split(" "))
